/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableView.java
 *
 * Created on Apr 29, 2013, 2:22:57 PM
 */
package com.project.ui;

import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RavirajS
 */
public class TableView extends javax.swing.JDialog {

    DefaultTableModel tableModel;
    ComboBoxModel cbModel;
    Vector<Object> originalData;
    Vector<String> columns;

    /** Creates new form TableView */
    public TableView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
            }
        });
        initComponents();
    }

    public TableView(Vector<Object> tableData, Vector<String> heading) {
        this(null, true);
        originalData = tableData;
        columns = heading;
        cbModel = new DefaultComboBoxModel(heading);
        filterField.setModel(cbModel);
        tableModel = (DefaultTableModel) tableResults.getModel();
        tableModel.setDataVector(originalData, columns);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableResults = new javax.swing.JTable();
        filterField = new javax.swing.JComboBox();
        filterValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableResults.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tableResults);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 810, 410);

        getContentPane().add(filterField);
        filterField.setBounds(90, 10, 240, 20);

        filterValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterValueKeyReleased(evt);
            }
        });
        getContentPane().add(filterValue);
        filterValue.setBounds(360, 10, 160, 20);

        jLabel1.setText("Filter:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 60, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterValueKeyReleased
        // TODO add your handling code here:
        tableModel.setDataVector(originalData, columns);
        int colIndex = filterField.getSelectedIndex();
        int colLimit = tableModel.getColumnCount();
        int rowLimit = tableModel.getRowCount();
        Vector<Object> filterData = new Vector<Object>();
        for (int i = 0; i < rowLimit; i++) {
            String value = (String) tableModel.getValueAt(i, colIndex);
            if (value.contains(filterValue.getText())) {
                filterData.add(originalData.get(i));
            }
        }
        tableModel.setDataVector(filterData, columns);

    }//GEN-LAST:event_filterValueKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Vector<Object> data = new Vector<Object>();
                Vector<String> heading = new Vector<String>();
                heading.add("col1");
                heading.add("col2");
                heading.add("col3");
                TableView view = new TableView(data, heading);
                view.setSize(650, 450);
                view.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox filterField;
    private javax.swing.JTextField filterValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableResults;
    // End of variables declaration//GEN-END:variables
}
